package top.r3944realms.lib39.example.core.register;

import net.minecraft.world.item.Item;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import top.r3944realms.lib39.Lib39;
import top.r3944realms.lib39.example.content.item.ForgeFabricItem;
import top.r3944realms.lib39.example.content.item.ForgeItem;
import top.r3944realms.lib39.example.content.item.ForgeNeoForgeItem;

/**
 * The type Ex lib 39 items.
 */
public class ForgeExLib39Items {
    /**
     * The constant ITEMS.
     */
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Lib39.MOD_ID);

    static  {
        ExLib39Items.FABRIC = ITEMS.register(
                "fabric",
                () -> new ForgeFabricItem(
                        new Item.Properties()
                                .stacksTo(1)
                                .fireResistant()
                )
        );
        ExLib39Items.NEOFORGE =
                ITEMS.register("neoforge",
                        () -> new ForgeNeoForgeItem(
                                new Item.Properties()
                                        .stacksTo(1)
                                        .fireResistant()
                        ));
        ExLib39Items.FORGE =
                ITEMS.register("forge",
                        () -> new ForgeItem(
                                new Item.Properties()
                                        .stacksTo(1)
                                        .fireResistant()
                        ));

    }

    /**
     * Register.
     *
     * @param bus the bus
     */
    public static void register(IEventBus bus) {
        ITEMS.register(bus);
    }

}
