package top.r3944realms.lib39.base.datagen.provider;

import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeCategory;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.data.recipes.ShapelessRecipeBuilder;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Items;
import org.jetbrains.annotations.NotNull;
import top.r3944realms.lib39.content.register.Lib39Items;

import java.util.function.Consumer;

/**
 * The type Lib 39 recipe provider.
 */
public class Lib39RecipeProvider extends RecipeProvider {
    /**
     * Instantiates a new Lib 39 recipe provider.
     *
     * @param output the output
     */
    public Lib39RecipeProvider(PackOutput output) {
        super(output);
    }

    @Override
    protected void buildRecipes(@NotNull Consumer<FinishedRecipe> consumer) {
        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, Lib39Items.DOLL.get())
                .requires(ItemTags.WOOL)
                .requires(Items.ARMOR_STAND)
                .unlockedBy("has_armor_stand",has(Items.ARMOR_STAND))
                .save(consumer);
    }
}
