package top.r3944realms.lib39.content.register;

import net.minecraft.world.item.Item;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import top.r3944realms.lib39.Lib39;
import top.r3944realms.lib39.content.item.DollItem;

/**
 * The type Ex lib 39 items.
 */
public class Lib39Items {
    /**
     * The constant ITEMS.
     */
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Lib39.MOD_ID);

    /**
     * The constant DOLL.
     */
    public static final RegistryObject<Item> DOLL = ITEMS.register("doll", () -> new DollItem(new Item.Properties()));

    /**
     * Register.
     *
     * @param bus the bus
     */
    public static void register(IEventBus bus) {
        ITEMS.register(bus);
    }

}
