package top.r3944realms.lib39.content.register;

import net.minecraft.world.level.block.Block;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import top.r3944realms.lib39.Lib39;
import top.r3944realms.lib39.content.block.DollBlock;
import top.r3944realms.lib39.util.block.BlockRegistryBuilder;

/**
 * The type Lib 39 blocks.
 */
public class Lib39Blocks {
    /**
     * The constant BLOCKS.
     */
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, Lib39.MOD_ID);

    /**
     * The constant DOLL.
     */
    public static final RegistryObject<Block> DOLL = BlockRegistryBuilder
            .create()
            .withName("doll")
            .registerBlock(BLOCKS, DollBlock::new)
            .build();


    /**
     * Register.
     *
     * @param bus the bus
     */
    public static void register(IEventBus bus) {
        BLOCKS.register(bus);
    }
}
