package top.r3944realms.lib39.base.datagen.provider;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.*;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Items;
import top.r3944realms.lib39.core.register.Lib39Items;

import java.util.concurrent.CompletableFuture;

/**
 * The type Lib 39 recipe provider.
 */
public class Lib39RecipeProvider extends RecipeProvider {
    /**
     * Instantiates a new Lib 39 recipe provider.
     *
     * @param output     the output
     * @param registries the registries
     */
    public Lib39RecipeProvider(HolderLookup.Provider output, RecipeOutput recipeOutput) {
        super(output, recipeOutput);
    }

    @Override
    protected void buildRecipes() {
        this.shapeless(RecipeCategory.MISC, Lib39Items.DOLL.get())
                .requires(ItemTags.WOOL)
                .requires(Items.ARMOR_STAND)
                .unlockedBy("has_armor_stand",has(Items.ARMOR_STAND))
                .save(this.output);
    }
}
